// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solis.AgentePDV.Data;

#nullable disable

namespace Solis.AgentePDV.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    partial class LocalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Solis.AgentePDV.Models.Caixa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Diferenca")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroTerminal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperadorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperadorNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeVendas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sincronizado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCredito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDinheiro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalOutros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVendas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorAbertura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorFechamento")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DataAbertura");

                    b.HasIndex("NumeroTerminal");

                    b.HasIndex("Sincronizado");

                    b.HasIndex("Status");

                    b.HasIndex("NumeroTerminal", "Status");

                    b.ToTable("Caixas", (string)null);
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiBaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeAgente")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenValidoAte")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("Configuracoes", (string)null);
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("CNAE")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EnquadramentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MensagemCupom")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RegimeEspecialTributacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegimeTributarioId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SincronizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.HasIndex("EnquadramentoId");

                    b.HasIndex("RegimeEspecialTributacaoId");

                    b.HasIndex("RegimeTributarioId");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.Enquadramento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Enquadramentos", (string)null);
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.FormaPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bandeira")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaximoParcelas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PermiteTroco")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequerTEF")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sincronizado")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TaxaJuros")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativa");

                    b.HasIndex("Codigo");

                    b.HasIndex("Descricao");

                    b.HasIndex("Ordem");

                    b.HasIndex("Sincronizado");

                    b.HasIndex("Tipo");

                    b.HasIndex("Tipo", "Ativa");

                    b.ToTable("FormasPagamento", (string)null);
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointApi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EnviadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxTentativas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetodoHttp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProximaTentativaEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TentativasEnvio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaTentativaEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoErro")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UltimoStatusCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("ProximaTentativaEm");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "ProximaTentativaEm", "Prioridade");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CEST")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoInterno")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NCM")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SincronizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("CodigoBarras");

                    b.HasIndex("CodigoInterno");

                    b.HasIndex("Nome");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.ProdutoPreco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SincronizadoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("ProdutoId")
                        .IsUnique();

                    b.ToTable("ProdutoPrecos", (string)null);
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.RegimeEspecialTributacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("RegimesEspeciaisTributacao", (string)null);
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.RegimeTributario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AliquotaPadrao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("RegimesTributarios", (string)null);
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.StatusVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PermiteCancelamento")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PermiteEdicao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sincronizado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SincronizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StatusFinal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativa");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Ordem");

                    b.HasIndex("Sincronizado");

                    b.HasIndex("Ativa", "Ordem");

                    b.ToTable("StatusVendas", (string)null);
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CaixaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteCpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteNome")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErroSync")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EstabelecimentoId")
                        .HasColumnType("TEXT");

                    b.Property<long>("NumeroCupom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PdvId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sincronizado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SincronizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StatusVendaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TentativasSync")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorBruto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorLiquido")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CaixaId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NumeroCupom");

                    b.HasIndex("Sincronizado");

                    b.HasIndex("StatusVendaId");

                    b.ToTable("Vendas", (string)null);
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.VendaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DescontoItem")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("ProdutoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("Sequencia")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VendaId", "Sequencia")
                        .IsUnique();

                    b.ToTable("VendaItens", (string)null);
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.VendaPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Autorizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bandeira")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FormaPagamentoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NSU")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Parcelas")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorTroco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("VendaId");

                    b.ToTable("VendaPagamentos", (string)null);
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.Empresa", b =>
                {
                    b.HasOne("Solis.AgentePDV.Models.Enquadramento", "Enquadramento")
                        .WithMany()
                        .HasForeignKey("EnquadramentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Solis.AgentePDV.Models.RegimeEspecialTributacao", "RegimeEspecialTributacao")
                        .WithMany()
                        .HasForeignKey("RegimeEspecialTributacaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Solis.AgentePDV.Models.RegimeTributario", "RegimeTributario")
                        .WithMany()
                        .HasForeignKey("RegimeTributarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enquadramento");

                    b.Navigation("RegimeEspecialTributacao");

                    b.Navigation("RegimeTributario");
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.ProdutoPreco", b =>
                {
                    b.HasOne("Solis.AgentePDV.Models.Produto", "Produto")
                        .WithOne("PrecoAtual")
                        .HasForeignKey("Solis.AgentePDV.Models.ProdutoPreco", "ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.Venda", b =>
                {
                    b.HasOne("Solis.AgentePDV.Models.Caixa", "Caixa")
                        .WithMany("Vendas")
                        .HasForeignKey("CaixaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Solis.AgentePDV.Models.StatusVenda", "StatusVenda")
                        .WithMany("Vendas")
                        .HasForeignKey("StatusVendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caixa");

                    b.Navigation("StatusVenda");
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.VendaItem", b =>
                {
                    b.HasOne("Solis.AgentePDV.Models.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.VendaPagamento", b =>
                {
                    b.HasOne("Solis.AgentePDV.Models.FormaPagamento", "FormaPagamento")
                        .WithMany("Pagamentos")
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Solis.AgentePDV.Models.Venda", "Venda")
                        .WithMany("Pagamentos")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaPagamento");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.Caixa", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.FormaPagamento", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.Produto", b =>
                {
                    b.Navigation("PrecoAtual");
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.StatusVenda", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("Solis.AgentePDV.Models.Venda", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
